### ISSUE TITLE
Hide Stickers

### ISSUE THREAD

**Issue by Narsku** [NicolasDurant/stick_it#5]
Hello! (Sorry for bad english), im using your library trying to create frames for videos, the problem is that im want to hide the sticker selector, it is possible?, and can i create text stickers?

**Comment by NicolasDurant** [comment]
Hey!

I'm not the original owner of the package, just implemented it to be useable with null-safety. But as far as I can see:

- There is no way of removing the sticker selector other than setting the `panelHeight: 0` and then dynamically resetting the panel to a specific height, when you want to show the panel again. 
- The `stickerList` is of type `List<Image>`, so adding texts would just be possible, if you had them as prepared images.
